------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 3.4
--  \   \         Application : 7 Series FPGAs Transceivers Wizard 
--  /   /         Filename : gol_quad_gt_usrclk_source.vhd
-- /___/   /\      
-- \   \  /  \ 
--  \___\/\___\ 
--
--
-- Module gol_quad_GT_USRCLK_SOURCE (for use with GTs)
-- Generated by Xilinx 7 Series FPGAs Transceivers 7 Series FPGAs Transceivers Wizard
-- 
-- 
-- (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES. 


library ieee;
use ieee.std_logic_1164.all;

library UNISIM;
use UNISIM.VCOMPONENTS.ALL;

--***********************************Entity Declaration*******************************
entity gol_quad_GT_USRCLK_SOURCE is
port
(
    mmcm_reset : in std_logic;
    gt_refclk_in : in std_logic;
 
    GT_RXUSRCLK_OUT : out std_logic;
    GT_RXUSRCLK2_OUT : out std_logic;
    mmcm_locked : out std_logic
);
end gol_quad_GT_USRCLK_SOURCE;

architecture RTL of gol_quad_GT_USRCLK_SOURCE is

--*********************************Wire Declarations**********************************
signal clkfbout : std_logic;
signal gt_refclk_bufg : std_logic;
signal usrclk : std_logic;
signal usrclk_bufg : std_logic;

begin

plle_usrclk:  PLLE2_ADV
generic map (
    BANDWIDTH => "HIGH",  -- OPTIMIZED, HIGH, LOW
    CLKFBOUT_MULT => 23,        -- Multiply value for all CLKOUT, (2-64)
    CLKFBOUT_PHASE => 0.0,     -- Phase offset in degrees of CLKFB, (-360.000-360.000).
    -- CLKIN_PERIOD: Input clock period in nS to ps resolution (i.e. 33.333 is 30 MHz).
    CLKIN1_PERIOD => 1.559,
    CLKIN2_PERIOD => 0.0,
    -- CLKOUT0_DIVIDE - CLKOUT5_DIVIDE: Divide amount for CLKOUT (1-128)
    CLKOUT0_DIVIDE => 46,
    CLKOUT1_DIVIDE => 1,
    CLKOUT2_DIVIDE => 1,
    CLKOUT3_DIVIDE => 1,
    CLKOUT4_DIVIDE => 1,
    CLKOUT5_DIVIDE => 1,
    -- CLKOUT0_DUTY_CYCLE - CLKOUT5_DUTY_CYCLE: Duty cycle for CLKOUT outputs (0.001-0.999).
    CLKOUT0_DUTY_CYCLE => 0.5,
    CLKOUT1_DUTY_CYCLE => 0.5,
    CLKOUT2_DUTY_CYCLE => 0.5,
    CLKOUT3_DUTY_CYCLE => 0.5,
    CLKOUT4_DUTY_CYCLE => 0.5,
    CLKOUT5_DUTY_CYCLE => 0.5,
    -- CLKOUT0_PHASE - CLKOUT5_PHASE: Phase offset for CLKOUT outputs (-360.000-360.000).
    CLKOUT0_PHASE => 0.0,
    CLKOUT1_PHASE => 0.0,
    CLKOUT2_PHASE => 0.0,
    CLKOUT3_PHASE => 0.0,
    CLKOUT4_PHASE => 0.0,
    CLKOUT5_PHASE => 0.0,
    COMPENSATION => "ZHOLD",   -- ZHOLD, BUF_IN, EXTERNAL, INTERNAL
    DIVCLK_DIVIDE => 8,        -- Master division value (1-56)
    -- REF_JITTER: Reference input jitter in UI (0.000-0.999).
    REF_JITTER1 => 0.010,
    REF_JITTER2 => 0.0,
    STARTUP_WAIT => "FALSE"    -- Delay DONE until PLL Locks, ("TRUE"/"FALSE")
)
port map (
    -- Clock Outputs: 1-bit (each) output: User configurable clock outputs
    CLKOUT0 => usrclk,   -- 1-bit output: CLKOUT0
    CLKOUT1 => open,   -- 1-bit output: CLKOUT1
    CLKOUT2 => open,   -- 1-bit output: CLKOUT2
    CLKOUT3 => open,   -- 1-bit output: CLKOUT3
    CLKOUT4 => open,   -- 1-bit output: CLKOUT4
    CLKOUT5 => open,   -- 1-bit output: CLKOUT5
    -- DRP Ports: 16-bit (each) output: Dynamic reconfiguration ports
    DO => open,             -- 16-bit output: DRP data
    DRDY => open,         -- 1-bit output: DRP ready
    -- Feedback Clocks: 1-bit (each) output: Clock feedback ports
    CLKFBOUT => CLKFBOUT, -- 1-bit output: Feedback clock
    LOCKED => mmcm_locked,     -- 1-bit output: LOCK
    -- Clock Inputs: 1-bit (each) input: Clock inputs
    CLKIN1 => gt_refclk_bufg,     -- 1-bit input: Primary clock
    CLKIN2 => '0',     -- 1-bit input: Secondary clock
    -- Control Ports: 1-bit (each) input: PLL control ports
    CLKINSEL => '1', -- 1-bit input: Clock select, High=CLKIN1 Low=CLKIN2
    PWRDWN => '0',     -- 1-bit input: Power-down
    RST => mmcm_reset,           -- 1-bit input: Reset
    -- DRP Ports: 7-bit (each) input: Dynamic reconfiguration ports
    DADDR => (others => '0'),       -- 7-bit input: DRP address
    DCLK => '0',         -- 1-bit input: DRP clock
    DEN => '0',           -- 1-bit input: DRP enable
    DI => (others => '0'),             -- 16-bit input: DRP data
    DWE => '0',           -- 1-bit input: DRP write enable
    -- Feedback Clocks: 1-bit (each) input: Clock feedback ports
    CLKFBIN => clkfbout    -- 1-bit input: Feedback clock
);
    
refclk_bufg_i : BUFG
port map
(
    I => gt_refclk_in,
    O => gt_refclk_bufg
);

rxusrclk_bufg_i : BUFG
port map
(
    I => usrclk,
    O => usrclk_bufg
);

GT_RXUSRCLK_OUT <= usrclk_bufg;
GT_RXUSRCLK2_OUT <= usrclk_bufg;

end RTL;

