#should be always present after control FPGA is configured
create_clock -period 25.000 -name clk40_in [get_ports clk40_in]
#generated in control FPGA
create_clock -period 8.000 -name clk_125M [get_ports clk_125M]
#Chip2Chip data clock
create_clock -period 2.500 -name ext_clk_in [get_ports ext_clk_in]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property MARK_DEBUG true [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_start]
set_property MARK_DEBUG true [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_error]
set_property MARK_DEBUG true [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_done]




set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_sio_input_inst/axi_chip2chip_clk_gen_inst/m_aresetn]
set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_sio_input_inst/axi_chip2chip_clk_gen_inst/clk_locked]
set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/rx_user_reset]
set_property MARK_DEBUG true [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/idelay_ready]




set_property MARK_DEBUG true [get_nets {m_axi_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[11]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[22]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[7]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[28]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[30]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[4]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[19]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[15]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[1]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[4]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[18]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[9]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[17]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[1]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[25]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[31]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[6]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[4]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[6]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[0]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[26]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[0]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[3]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[29]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[5]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[24]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[20]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[7]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[14]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[0]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[6]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[27]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[7]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[3]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[13]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[2]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[8]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[2]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[5]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[23]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[1]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[10]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[21]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[16]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[2]}]
set_property MARK_DEBUG true [get_nets {m_axi_arlen[5]}]
set_property MARK_DEBUG true [get_nets {m_axi_araddr[12]}]
set_property MARK_DEBUG true [get_nets {m_axi_awlen[3]}]
set_property MARK_DEBUG true [get_nets {m_axi_awaddr[1]}]
set_property MARK_DEBUG true [get_nets m_axi_wvalid]
set_property MARK_DEBUG true [get_nets m_axi_rlast]
set_property MARK_DEBUG true [get_nets m_axi_awvalid]
set_property MARK_DEBUG true [get_nets m_axi_rvalid]
set_property MARK_DEBUG true [get_nets m_axi_wlast]
set_property MARK_DEBUG true [get_nets m_axi_rready]
set_property MARK_DEBUG true [get_nets m_axi_bready]
set_property MARK_DEBUG true [get_nets m_axi_wready]
set_property MARK_DEBUG true [get_nets m_axi_bvalid]
set_property MARK_DEBUG true [get_nets m_axi_arvalid]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/pat_count_reg__0[1]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/pat_count_reg__0[3]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/pat_count_reg__0[2]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/pat_count_reg__0[0]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[5]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[9]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[7]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[2]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[0]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[11]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[8]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[3]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[1]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[4]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[10]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/state[6]}]
set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/master_ack]
set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/master_nack]
set_property MARK_DEBUG false [get_nets m_pll/U0/LOCKED]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/n_0_state_reg[5]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/n_0_state_reg[6]}]
set_property MARK_DEBUG false [get_nets m_pll/U0/CLKIN1]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/n_0_state_reg[1]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/n_0_state_reg[0]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/n_0_state_reg[4]}]
set_property MARK_DEBUG false [get_nets ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/master_init]

set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[4]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[9]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[14]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[8]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[5]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[10]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[17]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[15]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[3]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[16]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[13]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[6]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[2]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[11]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[0]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[7]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[12]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/calib_data[1]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[5]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[0]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[14]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[15]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[9]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[13]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[16]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[10]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[4]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[11]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[3]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[17]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[2]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[8]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[6]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[12]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[1]}]
set_property MARK_DEBUG false [get_nets {ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/data_in[7]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk40_out_OBUF]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {axi_ipbus_bridge/addr[0]} {axi_ipbus_bridge/addr[1]} {axi_ipbus_bridge/addr[2]} {axi_ipbus_bridge/addr[3]} {axi_ipbus_bridge/addr[4]} {axi_ipbus_bridge/addr[5]} {axi_ipbus_bridge/addr[6]} {axi_ipbus_bridge/addr[7]} {axi_ipbus_bridge/addr[8]} {axi_ipbus_bridge/addr[9]} {axi_ipbus_bridge/addr[10]} {axi_ipbus_bridge/addr[11]} {axi_ipbus_bridge/addr[12]} {axi_ipbus_bridge/addr[13]} {axi_ipbus_bridge/addr[14]} {axi_ipbus_bridge/addr[15]} {axi_ipbus_bridge/addr[16]} {axi_ipbus_bridge/addr[17]} {axi_ipbus_bridge/addr[18]} {axi_ipbus_bridge/addr[19]} {axi_ipbus_bridge/addr[20]} {axi_ipbus_bridge/addr[21]} {axi_ipbus_bridge/addr[22]} {axi_ipbus_bridge/addr[23]} {axi_ipbus_bridge/addr[24]} {axi_ipbus_bridge/addr[25]} {axi_ipbus_bridge/addr[26]} {axi_ipbus_bridge/addr[27]} {axi_ipbus_bridge/addr[28]} {axi_ipbus_bridge/addr[29]} {axi_ipbus_bridge/addr[30]} {axi_ipbus_bridge/addr[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk200_out_OBUF]]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/idelay_ready]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list ctoc/inst/rx_user_clk]]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_done]]
create_debug_port u_ila_0 probe
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {axi_ipbus_bridge/bus_state[0]} {axi_ipbus_bridge/bus_state[1]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {m_axi_araddr[0]} {m_axi_araddr[1]} {m_axi_araddr[2]} {m_axi_araddr[3]} {m_axi_araddr[4]} {m_axi_araddr[5]} {m_axi_araddr[6]} {m_axi_araddr[7]} {m_axi_araddr[8]} {m_axi_araddr[9]} {m_axi_araddr[10]} {m_axi_araddr[11]} {m_axi_araddr[12]} {m_axi_araddr[13]} {m_axi_araddr[14]} {m_axi_araddr[15]} {m_axi_araddr[16]} {m_axi_araddr[17]} {m_axi_araddr[18]} {m_axi_araddr[19]} {m_axi_araddr[20]} {m_axi_araddr[21]} {m_axi_araddr[22]} {m_axi_araddr[23]} {m_axi_araddr[24]} {m_axi_araddr[25]} {m_axi_araddr[26]} {m_axi_araddr[27]} {m_axi_araddr[28]} {m_axi_araddr[29]} {m_axi_araddr[30]} {m_axi_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {m_axi_arlen[0]} {m_axi_arlen[1]} {m_axi_arlen[2]} {m_axi_arlen[3]} {m_axi_arlen[4]} {m_axi_arlen[5]} {m_axi_arlen[6]} {m_axi_arlen[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ipb_master_out[ipb_addr][0]} {ipb_master_out[ipb_addr][1]} {ipb_master_out[ipb_addr][2]} {ipb_master_out[ipb_addr][3]} {ipb_master_out[ipb_addr][4]} {ipb_master_out[ipb_addr][5]} {ipb_master_out[ipb_addr][6]} {ipb_master_out[ipb_addr][7]} {ipb_master_out[ipb_addr][8]} {ipb_master_out[ipb_addr][9]} {ipb_master_out[ipb_addr][10]} {ipb_master_out[ipb_addr][11]} {ipb_master_out[ipb_addr][12]} {ipb_master_out[ipb_addr][13]} {ipb_master_out[ipb_addr][14]} {ipb_master_out[ipb_addr][15]} {ipb_master_out[ipb_addr][16]} {ipb_master_out[ipb_addr][17]} {ipb_master_out[ipb_addr][18]} {ipb_master_out[ipb_addr][19]} {ipb_master_out[ipb_addr][20]} {ipb_master_out[ipb_addr][21]} {ipb_master_out[ipb_addr][22]} {ipb_master_out[ipb_addr][23]} {ipb_master_out[ipb_addr][24]} {ipb_master_out[ipb_addr][25]} {ipb_master_out[ipb_addr][26]} {ipb_master_out[ipb_addr][27]} {ipb_master_out[ipb_addr][28]} {ipb_master_out[ipb_addr][29]} {ipb_master_out[ipb_addr][30]} {ipb_master_out[ipb_addr][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {m_axi_awaddr[0]} {m_axi_awaddr[1]} {m_axi_awaddr[2]} {m_axi_awaddr[3]} {m_axi_awaddr[4]} {m_axi_awaddr[5]} {m_axi_awaddr[6]} {m_axi_awaddr[7]} {m_axi_awaddr[8]} {m_axi_awaddr[9]} {m_axi_awaddr[10]} {m_axi_awaddr[11]} {m_axi_awaddr[12]} {m_axi_awaddr[13]} {m_axi_awaddr[14]} {m_axi_awaddr[15]} {m_axi_awaddr[16]} {m_axi_awaddr[17]} {m_axi_awaddr[18]} {m_axi_awaddr[19]} {m_axi_awaddr[20]} {m_axi_awaddr[21]} {m_axi_awaddr[22]} {m_axi_awaddr[23]} {m_axi_awaddr[24]} {m_axi_awaddr[25]} {m_axi_awaddr[26]} {m_axi_awaddr[27]} {m_axi_awaddr[28]} {m_axi_awaddr[29]} {m_axi_awaddr[30]} {m_axi_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ipb_master_out[ipb_wdata][0]} {ipb_master_out[ipb_wdata][1]} {ipb_master_out[ipb_wdata][2]} {ipb_master_out[ipb_wdata][3]} {ipb_master_out[ipb_wdata][4]} {ipb_master_out[ipb_wdata][5]} {ipb_master_out[ipb_wdata][6]} {ipb_master_out[ipb_wdata][7]} {ipb_master_out[ipb_wdata][8]} {ipb_master_out[ipb_wdata][9]} {ipb_master_out[ipb_wdata][10]} {ipb_master_out[ipb_wdata][11]} {ipb_master_out[ipb_wdata][12]} {ipb_master_out[ipb_wdata][13]} {ipb_master_out[ipb_wdata][14]} {ipb_master_out[ipb_wdata][15]} {ipb_master_out[ipb_wdata][16]} {ipb_master_out[ipb_wdata][17]} {ipb_master_out[ipb_wdata][18]} {ipb_master_out[ipb_wdata][19]} {ipb_master_out[ipb_wdata][20]} {ipb_master_out[ipb_wdata][21]} {ipb_master_out[ipb_wdata][22]} {ipb_master_out[ipb_wdata][23]} {ipb_master_out[ipb_wdata][24]} {ipb_master_out[ipb_wdata][25]} {ipb_master_out[ipb_wdata][26]} {ipb_master_out[ipb_wdata][27]} {ipb_master_out[ipb_wdata][28]} {ipb_master_out[ipb_wdata][29]} {ipb_master_out[ipb_wdata][30]} {ipb_master_out[ipb_wdata][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ipb_master_in[ipb_rdata][0]} {ipb_master_in[ipb_rdata][1]} {ipb_master_in[ipb_rdata][2]} {ipb_master_in[ipb_rdata][3]} {ipb_master_in[ipb_rdata][4]} {ipb_master_in[ipb_rdata][5]} {ipb_master_in[ipb_rdata][6]} {ipb_master_in[ipb_rdata][7]} {ipb_master_in[ipb_rdata][8]} {ipb_master_in[ipb_rdata][9]} {ipb_master_in[ipb_rdata][10]} {ipb_master_in[ipb_rdata][11]} {ipb_master_in[ipb_rdata][12]} {ipb_master_in[ipb_rdata][13]} {ipb_master_in[ipb_rdata][14]} {ipb_master_in[ipb_rdata][15]} {ipb_master_in[ipb_rdata][16]} {ipb_master_in[ipb_rdata][17]} {ipb_master_in[ipb_rdata][18]} {ipb_master_in[ipb_rdata][19]} {ipb_master_in[ipb_rdata][20]} {ipb_master_in[ipb_rdata][21]} {ipb_master_in[ipb_rdata][22]} {ipb_master_in[ipb_rdata][23]} {ipb_master_in[ipb_rdata][24]} {ipb_master_in[ipb_rdata][25]} {ipb_master_in[ipb_rdata][26]} {ipb_master_in[ipb_rdata][27]} {ipb_master_in[ipb_rdata][28]} {ipb_master_in[ipb_rdata][29]} {ipb_master_in[ipb_rdata][30]} {ipb_master_in[ipb_rdata][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {m_axi_awlen[0]} {m_axi_awlen[1]} {m_axi_awlen[2]} {m_axi_awlen[3]} {m_axi_awlen[4]} {m_axi_awlen[5]} {m_axi_awlen[6]} {m_axi_awlen[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list axi_c2c_link_status]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list axi_c2c_multi_bit_error]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ipb_master_in[ipb_ack]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {ipb_master_in[ipb_err]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {ipb_master_out[ipb_strobe]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {ipb_master_out[ipb_write]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list m_axi_arvalid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list m_axi_awvalid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list m_axi_bready]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list m_axi_bvalid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list m_axi_rlast]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list m_axi_rready]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list m_axi_rvalid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list m_axi_wlast]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list m_axi_wready]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list m_axi_wvalid]]
create_debug_port u_ila_2 probe
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_error]]
create_debug_port u_ila_2 probe
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list ctoc/inst/slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.axi_chip2chip_phy_calib_inst/calib_start]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk40_out_OBUF]
