------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version : 3.4
--  \   \         Application : 7 Series FPGAs Transceivers Wizard 
--  /   /         Filename : gol_quad_support.vhd
-- /___/   /\      
-- \   \  /  \ 
--  \___\/\___\
--
--  Description : This module instantiates the modules required for
--                reset and initialisation of the Transceiver
--
-- Module gol_quad_support
-- Generated by Xilinx 7 Series FPGAs Transceivers Wizard
-- 
-- 
-- (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES. 


library ieee;
use ieee.std_logic_1164.all;
use work.links_pkg.all;

--***********************************Entity Declaration************************

entity gol_quad_wrapper is
generic
(
    EXAMPLE_SIM_GTRESET_SPEEDUP             : string    := "TRUE";     -- simulation setting for GT SecureIP model
    STABLE_CLOCK_PERIOD                     : integer   := 25 
);
port
(   --____________________________COMMON PORTS________________________________
    DRP_CLK_IN                 : in std_logic;
    SOFT_RESET_IN              : in std_logic_vector(3 downto 0);
    GT_REFCLK_IN               : in std_logic;
    GT_RXUSRCLK_IN             : in std_logic;
    GT_RXUSRCLK2_IN             : in std_logic;
    --____________________________CHANNEL PORTS________________________________
    --------------------------------- CPLL Ports -------------------------------
    gt_cpllfbclklost_out                   : out  std_logic_vector(3 downto 0);
    gt_cplllock_out                        : out  std_logic_vector(3 downto 0);
    gt_cpllpd_in                           : in   std_logic_vector(3 downto 0);
    gt_cpllreset_in                        : in   std_logic_vector(3 downto 0);
    -------------------------- Channel - Clocking Ports ------------------------
    gt_gtgrefclk_in                        : in   std_logic_vector(3 downto 0);
    gt_gtnorthrefclk0_in                   : in   std_logic_vector(3 downto 0);
    gt_gtnorthrefclk1_in                   : in   std_logic_vector(3 downto 0);
    gt_gtrefclk1_in                        : in   std_logic_vector(3 downto 0);
    gt_gtsouthrefclk0_in                   : in   std_logic_vector(3 downto 0);
    gt_gtsouthrefclk1_in                   : in   std_logic_vector(3 downto 0);
    ---------------------------- Channel - DRP Ports  --------------------------
    gt_drpaddr_in                          : in   t_9b_array(3 downto 0);
    gt_drpdi_in                            : in   t_16b_array(3 downto 0);
    gt_drpdo_out                           : out  t_16b_array(3 downto 0);
    gt_drpen_in                            : in   std_logic_vector(3 downto 0);
    gt_drprdy_out                          : out  std_logic_vector(3 downto 0);
    gt_drpwe_in                            : in   std_logic_vector(3 downto 0);
    --------------------- RX Initialization and Reset Ports --------------------
    gt_eyescanreset_in                     : in   std_logic_vector(3 downto 0);
    gt_rxuserrdy_in                        : in   std_logic_vector(3 downto 0);
    -------------------------- RX Margin Analysis Ports ------------------------
    gt_eyescandataerror_out                : out  std_logic_vector(3 downto 0);
    gt_eyescantrigger_in                   : in   std_logic_vector(3 downto 0);
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt_dmonitorout_out                     : out  t_15b_array(3 downto 0);
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt_rxdata_out                          : out  t_32b_array(3 downto 0);
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt_rxdisperr_out                       : out  t_4b_array(3 downto 0);
    gt_rxnotintable_out                    : out  t_4b_array(3 downto 0);
    gt_rxchariscomma_out                   : out  t_4b_array(3 downto 0);
    gt_rxcharisk_out                       : out  t_4b_array(3 downto 0);
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt_gthrxp_in                           : in   std_logic_vector(3 downto 0);
    gt_gthrxn_in                           : in   std_logic_vector(3 downto 0);
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt_rxbufstatus_out                     : out  t_3b_array(3 downto 0);
    gt_rxphmonitor_out                     : out  t_5b_array(3 downto 0);
    gt_rxphslipmonitor_out                 : out  t_5b_array(3 downto 0);
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt_rxbyteisaligned_out                 : out  std_logic_vector(3 downto 0);
    gt_rxbyterealign_out                   : out  std_logic_vector(3 downto 0);
    gt_rxcommadet_out                      : out  std_logic_vector(3 downto 0);
    gt_rxmcommaalignen_in                  : in   std_logic_vector(3 downto 0);
    gt_rxpcommaalignen_in                  : in   std_logic_vector(3 downto 0);
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt_rxmonitorout_out                    : out  t_7b_array(3 downto 0);
    gt_rxmonitorsel_in                     : in   t_2b_array(3 downto 0);
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt_gtrxreset_in                        : in   std_logic_vector(3 downto 0);
    gt_rxpcsreset_in                       : in   std_logic_vector(3 downto 0);
    gt_rxpmareset_in                       : in   std_logic_vector(3 downto 0);
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt_rxpolarity_in                       : in   std_logic_vector(3 downto 0);
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt_rxresetdone_out                     : out  std_logic_vector(3 downto 0);
    --------------------- TX Initialization and Reset Ports --------------------
    gt_gttxreset_in                        : in   std_logic_vector(3 downto 0)
);

end gol_quad_wrapper;
    
architecture RTL of gol_quad_wrapper is
attribute DowngradeIPIdentifiedWarnings: string;
attribute DowngradeIPIdentifiedWarnings of RTL : architecture is "yes";

--**************************Component Declarations*****************************

component gol_quad
 
port
(
    SYSCLK_IN                               : in   std_logic;
    SOFT_RESET_IN                           : in   std_logic_vector(3 downto 0);
    DONT_RESET_ON_DATA_ERROR_IN             : in   std_logic;
    GT0_DRP_BUSY_OUT                        : out  std_logic;
    GT0_TX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT0_RX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT1_DRP_BUSY_OUT                        : out  std_logic;
    GT1_TX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT1_RX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT2_DRP_BUSY_OUT                        : out  std_logic;
    GT2_TX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT2_RX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT3_DRP_BUSY_OUT                        : out  std_logic;
    GT3_TX_FSM_RESET_DONE_OUT               : out  std_logic;
    GT3_RX_FSM_RESET_DONE_OUT               : out  std_logic;

    --_________________________________________________________________________
    --GT0  (X0Y0)
    --____________________________CHANNEL PORTS________________________________
    --------------------------------- CPLL Ports -------------------------------
    gt0_cpllfbclklost_out                   : out  std_logic;
    gt0_cplllock_out                        : out  std_logic;
    gt0_cplllockdetclk_in                   : in   std_logic;
    gt0_cpllpd_in                           : in   std_logic;
    gt0_cpllreset_in                        : in   std_logic;
    -------------------------- Channel - Clocking Ports ------------------------
    gt0_gtgrefclk_in                        : in   std_logic;
    gt0_gtnorthrefclk0_in                   : in   std_logic;
    gt0_gtnorthrefclk1_in                   : in   std_logic;
    gt0_gtrefclk0_in                        : in   std_logic;
    gt0_gtrefclk1_in                        : in   std_logic;
    gt0_gtsouthrefclk0_in                   : in   std_logic;
    gt0_gtsouthrefclk1_in                   : in   std_logic;
    ---------------------------- Channel - DRP Ports  --------------------------
    gt0_drpaddr_in                          : in   std_logic_vector(8 downto 0);
    gt0_drpclk_in                           : in   std_logic;
    gt0_drpdi_in                            : in   std_logic_vector(15 downto 0);
    gt0_drpdo_out                           : out  std_logic_vector(15 downto 0);
    gt0_drpen_in                            : in   std_logic;
    gt0_drprdy_out                          : out  std_logic;
    gt0_drpwe_in                            : in   std_logic;
    --------------------- RX Initialization and Reset Ports --------------------
    gt0_eyescanreset_in                     : in   std_logic;
    gt0_rxuserrdy_in                        : in   std_logic;
    -------------------------- RX Margin Analysis Ports ------------------------
    gt0_eyescandataerror_out                : out  std_logic;
    gt0_eyescantrigger_in                   : in   std_logic;
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt0_dmonitorout_out                     : out  std_logic_vector(14 downto 0);
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt0_rxusrclk_in                         : in   std_logic;
    gt0_rxusrclk2_in                        : in   std_logic;
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt0_rxdata_out                          : out  std_logic_vector(31 downto 0);
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt0_rxdisperr_out                       : out  std_logic_vector(3 downto 0);
    gt0_rxnotintable_out                    : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt0_gthrxn_in                           : in   std_logic;
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt0_rxbufstatus_out                     : out  std_logic_vector(2 downto 0);
    gt0_rxphmonitor_out                     : out  std_logic_vector(4 downto 0);
    gt0_rxphslipmonitor_out                 : out  std_logic_vector(4 downto 0);
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt0_rxbyteisaligned_out                 : out  std_logic;
    gt0_rxbyterealign_out                   : out  std_logic;
    gt0_rxcommadet_out                      : out  std_logic;
    gt0_rxmcommaalignen_in                  : in   std_logic;
    gt0_rxpcommaalignen_in                  : in   std_logic;
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt0_rxmonitorout_out                    : out  std_logic_vector(6 downto 0);
    gt0_rxmonitorsel_in                     : in   std_logic_vector(1 downto 0);
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt0_rxoutclk_out                        : out  std_logic;
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt0_gtrxreset_in                        : in   std_logic;
    gt0_rxpcsreset_in                       : in   std_logic;
    gt0_rxpmareset_in                       : in   std_logic;
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt0_rxpolarity_in                       : in   std_logic;
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt0_rxchariscomma_out                   : out  std_logic_vector(3 downto 0);
    gt0_rxcharisk_out                       : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt0_gthrxp_in                           : in   std_logic;
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt0_rxresetdone_out                     : out  std_logic;
    --------------------- TX Initialization and Reset Ports --------------------
    gt0_gttxreset_in                        : in   std_logic;

    --GT1  (X0Y1)
    --____________________________CHANNEL PORTS________________________________
    --------------------------------- CPLL Ports -------------------------------
    gt1_cpllfbclklost_out                   : out  std_logic;
    gt1_cplllock_out                        : out  std_logic;
    gt1_cplllockdetclk_in                   : in   std_logic;
    gt1_cpllpd_in                           : in   std_logic;
    gt1_cpllreset_in                        : in   std_logic;
    -------------------------- Channel - Clocking Ports ------------------------
    gt1_gtgrefclk_in                        : in   std_logic;
    gt1_gtnorthrefclk0_in                   : in   std_logic;
    gt1_gtnorthrefclk1_in                   : in   std_logic;
    gt1_gtrefclk0_in                        : in   std_logic;
    gt1_gtrefclk1_in                        : in   std_logic;
    gt1_gtsouthrefclk0_in                   : in   std_logic;
    gt1_gtsouthrefclk1_in                   : in   std_logic;
    ---------------------------- Channel - DRP Ports  --------------------------
    gt1_drpaddr_in                          : in   std_logic_vector(8 downto 0);
    gt1_drpclk_in                           : in   std_logic;
    gt1_drpdi_in                            : in   std_logic_vector(15 downto 0);
    gt1_drpdo_out                           : out  std_logic_vector(15 downto 0);
    gt1_drpen_in                            : in   std_logic;
    gt1_drprdy_out                          : out  std_logic;
    gt1_drpwe_in                            : in   std_logic;
    --------------------- RX Initialization and Reset Ports --------------------
    gt1_eyescanreset_in                     : in   std_logic;
    gt1_rxuserrdy_in                        : in   std_logic;
    -------------------------- RX Margin Analysis Ports ------------------------
    gt1_eyescandataerror_out                : out  std_logic;
    gt1_eyescantrigger_in                   : in   std_logic;
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt1_dmonitorout_out                     : out  std_logic_vector(14 downto 0);
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt1_rxusrclk_in                         : in   std_logic;
    gt1_rxusrclk2_in                        : in   std_logic;
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt1_rxdata_out                          : out  std_logic_vector(31 downto 0);
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt1_rxdisperr_out                       : out  std_logic_vector(3 downto 0);
    gt1_rxnotintable_out                    : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt1_gthrxn_in                           : in   std_logic;
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt1_rxbufstatus_out                     : out  std_logic_vector(2 downto 0);
    gt1_rxphmonitor_out                     : out  std_logic_vector(4 downto 0);
    gt1_rxphslipmonitor_out                 : out  std_logic_vector(4 downto 0);
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt1_rxbyteisaligned_out                 : out  std_logic;
    gt1_rxbyterealign_out                   : out  std_logic;
    gt1_rxcommadet_out                      : out  std_logic;
    gt1_rxmcommaalignen_in                  : in   std_logic;
    gt1_rxpcommaalignen_in                  : in   std_logic;
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt1_rxmonitorout_out                    : out  std_logic_vector(6 downto 0);
    gt1_rxmonitorsel_in                     : in   std_logic_vector(1 downto 0);
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt1_rxoutclk_out                        : out  std_logic;
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt1_gtrxreset_in                        : in   std_logic;
    gt1_rxpcsreset_in                       : in   std_logic;
    gt1_rxpmareset_in                       : in   std_logic;
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt1_rxpolarity_in                       : in   std_logic;
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt1_rxchariscomma_out                   : out  std_logic_vector(3 downto 0);
    gt1_rxcharisk_out                       : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt1_gthrxp_in                           : in   std_logic;
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt1_rxresetdone_out                     : out  std_logic;
    --------------------- TX Initialization and Reset Ports --------------------
    gt1_gttxreset_in                        : in   std_logic;

    --GT2  (X0Y2)
    --____________________________CHANNEL PORTS________________________________
    --------------------------------- CPLL Ports -------------------------------
    gt2_cpllfbclklost_out                   : out  std_logic;
    gt2_cplllock_out                        : out  std_logic;
    gt2_cplllockdetclk_in                   : in   std_logic;
    gt2_cpllpd_in                           : in   std_logic;
    gt2_cpllreset_in                        : in   std_logic;
    -------------------------- Channel - Clocking Ports ------------------------
    gt2_gtgrefclk_in                        : in   std_logic;
    gt2_gtnorthrefclk0_in                   : in   std_logic;
    gt2_gtnorthrefclk1_in                   : in   std_logic;
    gt2_gtrefclk0_in                        : in   std_logic;
    gt2_gtrefclk1_in                        : in   std_logic;
    gt2_gtsouthrefclk0_in                   : in   std_logic;
    gt2_gtsouthrefclk1_in                   : in   std_logic;
    ---------------------------- Channel - DRP Ports  --------------------------
    gt2_drpaddr_in                          : in   std_logic_vector(8 downto 0);
    gt2_drpclk_in                           : in   std_logic;
    gt2_drpdi_in                            : in   std_logic_vector(15 downto 0);
    gt2_drpdo_out                           : out  std_logic_vector(15 downto 0);
    gt2_drpen_in                            : in   std_logic;
    gt2_drprdy_out                          : out  std_logic;
    gt2_drpwe_in                            : in   std_logic;
    --------------------- RX Initialization and Reset Ports --------------------
    gt2_eyescanreset_in                     : in   std_logic;
    gt2_rxuserrdy_in                        : in   std_logic;
    -------------------------- RX Margin Analysis Ports ------------------------
    gt2_eyescandataerror_out                : out  std_logic;
    gt2_eyescantrigger_in                   : in   std_logic;
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt2_dmonitorout_out                     : out  std_logic_vector(14 downto 0);
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt2_rxusrclk_in                         : in   std_logic;
    gt2_rxusrclk2_in                        : in   std_logic;
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt2_rxdata_out                          : out  std_logic_vector(31 downto 0);
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt2_rxdisperr_out                       : out  std_logic_vector(3 downto 0);
    gt2_rxnotintable_out                    : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt2_gthrxn_in                           : in   std_logic;
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt2_rxbufstatus_out                     : out  std_logic_vector(2 downto 0);
    gt2_rxphmonitor_out                     : out  std_logic_vector(4 downto 0);
    gt2_rxphslipmonitor_out                 : out  std_logic_vector(4 downto 0);
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt2_rxbyteisaligned_out                 : out  std_logic;
    gt2_rxbyterealign_out                   : out  std_logic;
    gt2_rxcommadet_out                      : out  std_logic;
    gt2_rxmcommaalignen_in                  : in   std_logic;
    gt2_rxpcommaalignen_in                  : in   std_logic;
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt2_rxmonitorout_out                    : out  std_logic_vector(6 downto 0);
    gt2_rxmonitorsel_in                     : in   std_logic_vector(1 downto 0);
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt2_rxoutclk_out                        : out  std_logic;
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt2_gtrxreset_in                        : in   std_logic;
    gt2_rxpcsreset_in                       : in   std_logic;
    gt2_rxpmareset_in                       : in   std_logic;
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt2_rxpolarity_in                       : in   std_logic;
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt2_rxchariscomma_out                   : out  std_logic_vector(3 downto 0);
    gt2_rxcharisk_out                       : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt2_gthrxp_in                           : in   std_logic;
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt2_rxresetdone_out                     : out  std_logic;
    --------------------- TX Initialization and Reset Ports --------------------
    gt2_gttxreset_in                        : in   std_logic;

    --GT3  (X0Y3)
    --____________________________CHANNEL PORTS________________________________
    --------------------------------- CPLL Ports -------------------------------
    gt3_cpllfbclklost_out                   : out  std_logic;
    gt3_cplllock_out                        : out  std_logic;
    gt3_cplllockdetclk_in                   : in   std_logic;
    gt3_cpllpd_in                           : in   std_logic;
    gt3_cpllreset_in                        : in   std_logic;
    -------------------------- Channel - Clocking Ports ------------------------
    gt3_gtgrefclk_in                        : in   std_logic;
    gt3_gtnorthrefclk0_in                   : in   std_logic;
    gt3_gtnorthrefclk1_in                   : in   std_logic;
    gt3_gtrefclk0_in                        : in   std_logic;
    gt3_gtrefclk1_in                        : in   std_logic;
    gt3_gtsouthrefclk0_in                   : in   std_logic;
    gt3_gtsouthrefclk1_in                   : in   std_logic;
    ---------------------------- Channel - DRP Ports  --------------------------
    gt3_drpaddr_in                          : in   std_logic_vector(8 downto 0);
    gt3_drpclk_in                           : in   std_logic;
    gt3_drpdi_in                            : in   std_logic_vector(15 downto 0);
    gt3_drpdo_out                           : out  std_logic_vector(15 downto 0);
    gt3_drpen_in                            : in   std_logic;
    gt3_drprdy_out                          : out  std_logic;
    gt3_drpwe_in                            : in   std_logic;
    --------------------- RX Initialization and Reset Ports --------------------
    gt3_eyescanreset_in                     : in   std_logic;
    gt3_rxuserrdy_in                        : in   std_logic;
    -------------------------- RX Margin Analysis Ports ------------------------
    gt3_eyescandataerror_out                : out  std_logic;
    gt3_eyescantrigger_in                   : in   std_logic;
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt3_dmonitorout_out                     : out  std_logic_vector(14 downto 0);
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt3_rxusrclk_in                         : in   std_logic;
    gt3_rxusrclk2_in                        : in   std_logic;
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt3_rxdata_out                          : out  std_logic_vector(31 downto 0);
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt3_rxdisperr_out                       : out  std_logic_vector(3 downto 0);
    gt3_rxnotintable_out                    : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt3_gthrxn_in                           : in   std_logic;
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt3_rxbufstatus_out                     : out  std_logic_vector(2 downto 0);
    gt3_rxphmonitor_out                     : out  std_logic_vector(4 downto 0);
    gt3_rxphslipmonitor_out                 : out  std_logic_vector(4 downto 0);
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt3_rxbyteisaligned_out                 : out  std_logic;
    gt3_rxbyterealign_out                   : out  std_logic;
    gt3_rxcommadet_out                      : out  std_logic;
    gt3_rxmcommaalignen_in                  : in   std_logic;
    gt3_rxpcommaalignen_in                  : in   std_logic;
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt3_rxmonitorout_out                    : out  std_logic_vector(6 downto 0);
    gt3_rxmonitorsel_in                     : in   std_logic_vector(1 downto 0);
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt3_rxoutclk_out                        : out  std_logic;
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt3_gtrxreset_in                        : in   std_logic;
    gt3_rxpcsreset_in                       : in   std_logic;
    gt3_rxpmareset_in                       : in   std_logic;
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt3_rxpolarity_in                       : in   std_logic;
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt3_rxchariscomma_out                   : out  std_logic_vector(3 downto 0);
    gt3_rxcharisk_out                       : out  std_logic_vector(3 downto 0);
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt3_gthrxp_in                           : in   std_logic;
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt3_rxresetdone_out                     : out  std_logic;
    --------------------- TX Initialization and Reset Ports --------------------
    gt3_gttxreset_in                        : in   std_logic;


    --____________________________COMMON PORTS________________________________
     GT0_QPLLOUTCLK_IN  : in std_logic;
     GT0_QPLLOUTREFCLK_IN : in std_logic

);

end component;


component gol_quad_common 
generic
(
    -- Simulation attributes
    WRAPPER_SIM_GTRESET_SPEEDUP     : string     :=  "FALSE"        -- Set to "TRUE" to speed up sim reset 
);
port
(
    GTGREFCLK_IN      : in std_logic;
    GTNORTHREFCLK0_IN : in std_logic;
    GTNORTHREFCLK1_IN : in std_logic;
    GTREFCLK1_IN      : in std_logic;
    GTSOUTHREFCLK0_IN : in std_logic;
    GTSOUTHREFCLK1_IN : in std_logic;
    GTREFCLK0_IN : in std_logic;
    QPLLLOCK_OUT : out std_logic;
    QPLLLOCKDETCLK_IN : in std_logic;
    QPLLOUTCLK_OUT : out std_logic;
    QPLLOUTREFCLK_OUT : out std_logic;
    QPLLREFCLKLOST_OUT : out std_logic;    
    QPLLRESET_IN : in std_logic

);

end component;


--***********************************Parameter Declarations********************

    constant DLY : time := 1 ns;

--**************************** Wire Declarations ******************************
--____________________________COMMON PORTS________________________________
signal gt0_qplllock_i : std_logic;
signal gt0_qpllrefclklost_i  : std_logic;
signal gt0_qpllreset_i  : std_logic;
signal gt0_qpllreset_t  : std_logic;
signal gt0_qplloutclk_i  : std_logic;
signal gt0_qplloutrefclk_i : std_logic;

------------------------------- Global Signals -----------------------------
signal  tied_to_ground_i                : std_logic;
signal  tied_to_ground_vec_i            : std_logic_vector(63 downto 0);
signal  tied_to_vcc_i                   : std_logic;
signal  tied_to_vcc_vec_i               : std_logic_vector(7 downto 0);


attribute keep: string;
    
signal commonreset_i : std_logic;

--**************************** Main Body of Code *******************************
begin

    --  Static signal Assigments
tied_to_ground_i                             <= '0';
tied_to_ground_vec_i                         <= x"0000000000000000";
tied_to_vcc_i                                <= '1';
tied_to_vcc_vec_i                            <= "11111111";


common0_i:gol_quad_common 
generic map
(
   WRAPPER_SIM_GTRESET_SPEEDUP => EXAMPLE_SIM_GTRESET_SPEEDUP
)
port map
   (
    GTGREFCLK_IN      => '0',
    GTNORTHREFCLK0_IN => '0',
    GTNORTHREFCLK1_IN => '0',
    GTREFCLK1_IN      => '0',
    GTSOUTHREFCLK0_IN => '0',
    GTSOUTHREFCLK1_IN => '0',
    GTREFCLK0_IN => gt_refclk_in,
    QPLLLOCK_OUT => open,
    QPLLLOCKDETCLK_IN => DRP_CLK_IN,
    QPLLOUTCLK_OUT => open,
    QPLLOUTREFCLK_OUT => open,
    QPLLREFCLKLOST_OUT => open,    
    QPLLRESET_IN => '1'

);


gol_quad_init_i : gol_quad
port map
(
    sysclk_in                       =>      DRP_CLK_IN,
    soft_reset_in                   =>      SOFT_RESET_IN,
    DONT_RESET_ON_DATA_ERROR_IN     => '1',
    --_____________________________________________________________________
    --_____________________________________________________________________
    --GT0  (X0Y0)
    --------------------------------- CPLL Ports -------------------------------
    gt0_cpllfbclklost_out           =>      gt_cpllfbclklost_out(0),
    gt0_cplllock_out                =>      gt_cplllock_out(0),
    gt0_cplllockdetclk_in           =>      DRP_CLK_IN,
    gt0_cpllpd_in                   =>      gt_cpllpd_in(0),
    gt0_cpllreset_in                =>      gt_cpllreset_in(0),
    -------------------------- Channel - Clocking Ports ------------------------
    gt0_gtgrefclk_in                =>      gt_gtgrefclk_in(0),
    gt0_gtnorthrefclk0_in           =>      gt_gtnorthrefclk0_in(0),
    gt0_gtnorthrefclk1_in           =>      gt_gtnorthrefclk1_in(0),
    gt0_gtrefclk0_in                =>      gt_refclk_in,
    gt0_gtrefclk1_in                =>      gt_gtrefclk1_in(0),
    gt0_gtsouthrefclk0_in           =>      gt_gtsouthrefclk0_in(0),
    gt0_gtsouthrefclk1_in           =>      gt_gtsouthrefclk1_in(0),
    ---------------------------- Channel - DRP Ports  --------------------------
    gt0_drpaddr_in                  =>      gt_drpaddr_in(0),
    gt0_drpclk_in                   =>      DRP_CLK_IN,
    gt0_drpdi_in                    =>      gt_drpdi_in(0),
    gt0_drpdo_out                   =>      gt_drpdo_out(0),
    gt0_drpen_in                    =>      gt_drpen_in(0),
    gt0_drprdy_out                  =>      gt_drprdy_out(0),
    gt0_drpwe_in                    =>      gt_drpwe_in(0),
    --------------------- RX Initialization and Reset Ports --------------------
    gt0_eyescanreset_in             =>      gt_eyescanreset_in(0),
    gt0_rxuserrdy_in                =>      gt_rxuserrdy_in(0),
    -------------------------- RX Margin Analysis Ports ------------------------
    gt0_eyescandataerror_out        =>      gt_eyescandataerror_out(0),
    gt0_eyescantrigger_in           =>      gt_eyescantrigger_in(0),
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt0_dmonitorout_out             =>      gt_dmonitorout_out(0),
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt0_rxusrclk_in                 =>      gt_rxusrclk_in,
    gt0_rxusrclk2_in                =>      gt_rxusrclk2_in,
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt0_rxdata_out                  =>      gt_rxdata_out(0),
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt0_rxdisperr_out               =>      gt_rxdisperr_out(0),
    gt0_rxnotintable_out            =>      gt_rxnotintable_out(0),
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt0_gthrxn_in                   =>      gt_gthrxn_in(0),
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt0_rxbufstatus_out             =>      gt_rxbufstatus_out(0),
    gt0_rxphmonitor_out             =>      gt_rxphmonitor_out(0),
    gt0_rxphslipmonitor_out         =>      gt_rxphslipmonitor_out(0),
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt0_rxbyteisaligned_out         =>      gt_rxbyteisaligned_out(0),
    gt0_rxbyterealign_out           =>      gt_rxbyterealign_out(0),
    gt0_rxcommadet_out              =>      gt_rxcommadet_out(0),
    gt0_rxmcommaalignen_in          =>      gt_rxmcommaalignen_in(0),
    gt0_rxpcommaalignen_in          =>      gt_rxpcommaalignen_in(0),
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt0_rxmonitorout_out            =>      gt_rxmonitorout_out(0),
    gt0_rxmonitorsel_in             =>      gt_rxmonitorsel_in(0),
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt0_rxoutclk_out                =>      open,
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt0_gtrxreset_in                =>      gt_gtrxreset_in(0),
    gt0_rxpcsreset_in               =>      gt_rxpcsreset_in(0),
    gt0_rxpmareset_in               =>      gt_rxpmareset_in(0),
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt0_rxpolarity_in               =>      gt_rxpolarity_in(0),
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt0_rxchariscomma_out           =>      gt_rxchariscomma_out(0),
    gt0_rxcharisk_out               =>      gt_rxcharisk_out(0),
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt0_gthrxp_in                   =>      gt_gthrxp_in(0),
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt0_rxresetdone_out             =>      gt_rxresetdone_out(0),
    --------------------- TX Initialization and Reset Ports --------------------
    gt0_gttxreset_in                =>      gt_gttxreset_in(0),
    --_____________________________________________________________________
    --_____________________________________________________________________
    --GT1  (X0Y1)
    --------------------------------- CPLL Ports -------------------------------
    gt1_cpllfbclklost_out           =>      gt_cpllfbclklost_out(1),
    gt1_cplllock_out                =>      gt_cplllock_out(1),
    gt1_cplllockdetclk_in           =>      DRP_CLK_IN,
    gt1_cpllpd_in                   =>      gt_cpllpd_in(1),
    gt1_cpllreset_in                =>      gt_cpllreset_in(1),
    -------------------------- Channel - Clocking Ports ------------------------
    gt1_gtgrefclk_in                =>      gt_gtgrefclk_in(1),
    gt1_gtnorthrefclk0_in           =>      gt_gtnorthrefclk0_in(1),
    gt1_gtnorthrefclk1_in           =>      gt_gtnorthrefclk1_in(1),
    gt1_gtrefclk0_in                =>      gt_refclk_in,
    gt1_gtrefclk1_in                =>      gt_gtrefclk1_in(1),
    gt1_gtsouthrefclk0_in           =>      gt_gtsouthrefclk0_in(1),
    gt1_gtsouthrefclk1_in           =>      gt_gtsouthrefclk1_in(1),
    ---------------------------- Channel - DRP Ports  --------------------------
    gt1_drpaddr_in                  =>      gt_drpaddr_in(1),
    gt1_drpclk_in                   =>      DRP_CLK_IN,
    gt1_drpdi_in                    =>      gt_drpdi_in(1),
    gt1_drpdo_out                   =>      gt_drpdo_out(1),
    gt1_drpen_in                    =>      gt_drpen_in(1),
    gt1_drprdy_out                  =>      gt_drprdy_out(1),
    gt1_drpwe_in                    =>      gt_drpwe_in(1),
    --------------------- RX Initialization and Reset Ports --------------------
    gt1_eyescanreset_in             =>      gt_eyescanreset_in(1),
    gt1_rxuserrdy_in                =>      gt_rxuserrdy_in(1),
    -------------------------- RX Margin Analysis Ports ------------------------
    gt1_eyescandataerror_out        =>      gt_eyescandataerror_out(1),
    gt1_eyescantrigger_in           =>      gt_eyescantrigger_in(1),
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt1_dmonitorout_out             =>      gt_dmonitorout_out(1),
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt1_rxusrclk_in                 =>      gt_rxusrclk_in,
    gt1_rxusrclk2_in                =>      gt_rxusrclk2_in,
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt1_rxdata_out                  =>      gt_rxdata_out(1),
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt1_rxdisperr_out               =>      gt_rxdisperr_out(1),
    gt1_rxnotintable_out            =>      gt_rxnotintable_out(1),
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt1_gthrxn_in                   =>      gt_gthrxn_in(1),
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt1_rxbufstatus_out             =>      gt_rxbufstatus_out(1),
    gt1_rxphmonitor_out             =>      gt_rxphmonitor_out(1),
    gt1_rxphslipmonitor_out         =>      gt_rxphslipmonitor_out(1),
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt1_rxbyteisaligned_out         =>      gt_rxbyteisaligned_out(1),
    gt1_rxbyterealign_out           =>      gt_rxbyterealign_out(1),
    gt1_rxcommadet_out              =>      gt_rxcommadet_out(1),
    gt1_rxmcommaalignen_in          =>      gt_rxmcommaalignen_in(1),
    gt1_rxpcommaalignen_in          =>      gt_rxpcommaalignen_in(1),
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt1_rxmonitorout_out            =>      gt_rxmonitorout_out(1),
    gt1_rxmonitorsel_in             =>      gt_rxmonitorsel_in(1),
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt1_rxoutclk_out                =>      open,
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt1_gtrxreset_in                =>      gt_gtrxreset_in(1),
    gt1_rxpcsreset_in               =>      gt_rxpcsreset_in(1),
    gt1_rxpmareset_in               =>      gt_rxpmareset_in(1),
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt1_rxpolarity_in               =>      gt_rxpolarity_in(1),
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt1_rxchariscomma_out           =>      gt_rxchariscomma_out(1),
    gt1_rxcharisk_out               =>      gt_rxcharisk_out(1),
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt1_gthrxp_in                   =>      gt_gthrxp_in(1),
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt1_rxresetdone_out             =>      gt_rxresetdone_out(1),
    --------------------- TX Initialization and Reset Ports --------------------
    gt1_gttxreset_in                =>      gt_gttxreset_in(1),
    --_____________________________________________________________________
    --_____________________________________________________________________
    --GT2  (X0Y2)
    --------------------------------- CPLL Ports -------------------------------
    gt2_cpllfbclklost_out           =>      gt_cpllfbclklost_out(2),
    gt2_cplllock_out                =>      gt_cplllock_out(2),
    gt2_cplllockdetclk_in           =>      DRP_CLK_IN,
    gt2_cpllpd_in                   =>      gt_cpllpd_in(2),
    gt2_cpllreset_in                =>      gt_cpllreset_in(2),
    -------------------------- Channel - Clocking Ports ------------------------
    gt2_gtgrefclk_in                =>      gt_gtgrefclk_in(2),
    gt2_gtnorthrefclk0_in           =>      gt_gtnorthrefclk0_in(2),
    gt2_gtnorthrefclk1_in           =>      gt_gtnorthrefclk1_in(2),
    gt2_gtrefclk0_in                =>      gt_refclk_in,
    gt2_gtrefclk1_in                =>      gt_gtrefclk1_in(2),
    gt2_gtsouthrefclk0_in           =>      gt_gtsouthrefclk0_in(2),
    gt2_gtsouthrefclk1_in           =>      gt_gtsouthrefclk1_in(2),
    ---------------------------- Channel - DRP Ports  --------------------------
    gt2_drpaddr_in                  =>      gt_drpaddr_in(2),
    gt2_drpclk_in                   =>      DRP_CLK_IN,
    gt2_drpdi_in                    =>      gt_drpdi_in(2),
    gt2_drpdo_out                   =>      gt_drpdo_out(2),
    gt2_drpen_in                    =>      gt_drpen_in(2),
    gt2_drprdy_out                  =>      gt_drprdy_out(2),
    gt2_drpwe_in                    =>      gt_drpwe_in(2),
    --------------------- RX Initialization and Reset Ports --------------------
    gt2_eyescanreset_in             =>      gt_eyescanreset_in(2),
    gt2_rxuserrdy_in                =>      gt_rxuserrdy_in(2),
    -------------------------- RX Margin Analysis Ports ------------------------
    gt2_eyescandataerror_out        =>      gt_eyescandataerror_out(2),
    gt2_eyescantrigger_in           =>      gt_eyescantrigger_in(2),
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt2_dmonitorout_out             =>      gt_dmonitorout_out(2),
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt2_rxusrclk_in                 =>      gt_rxusrclk_in,
    gt2_rxusrclk2_in                =>      gt_rxusrclk2_in,
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt2_rxdata_out                  =>      gt_rxdata_out(2),
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt2_rxdisperr_out               =>      gt_rxdisperr_out(2),
    gt2_rxnotintable_out            =>      gt_rxnotintable_out(2),
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt2_gthrxn_in                   =>      gt_gthrxn_in(2),
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt2_rxbufstatus_out             =>      gt_rxbufstatus_out(2),
    gt2_rxphmonitor_out             =>      gt_rxphmonitor_out(2),
    gt2_rxphslipmonitor_out         =>      gt_rxphslipmonitor_out(2),
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt2_rxbyteisaligned_out         =>      gt_rxbyteisaligned_out(2),
    gt2_rxbyterealign_out           =>      gt_rxbyterealign_out(2),
    gt2_rxcommadet_out              =>      gt_rxcommadet_out(2),
    gt2_rxmcommaalignen_in          =>      gt_rxmcommaalignen_in(2),
    gt2_rxpcommaalignen_in          =>      gt_rxpcommaalignen_in(2),
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt2_rxmonitorout_out            =>      gt_rxmonitorout_out(2),
    gt2_rxmonitorsel_in             =>      gt_rxmonitorsel_in(2),
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt2_rxoutclk_out                =>      open,
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt2_gtrxreset_in                =>      gt_gtrxreset_in(2),
    gt2_rxpcsreset_in               =>      gt_rxpcsreset_in(2),
    gt2_rxpmareset_in               =>      gt_rxpmareset_in(2),
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt2_rxpolarity_in               =>      gt_rxpolarity_in(2),
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt2_rxchariscomma_out           =>      gt_rxchariscomma_out(2),
    gt2_rxcharisk_out               =>      gt_rxcharisk_out(2),
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt2_gthrxp_in                   =>      gt_gthrxp_in(2),
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt2_rxresetdone_out             =>      gt_rxresetdone_out(2),
    --------------------- TX Initialization and Reset Ports --------------------
    gt2_gttxreset_in                =>      gt_gttxreset_in(2),
    --_____________________________________________________________________
    --_____________________________________________________________________
    --GT3  (X0Y3)
    --------------------------------- CPLL Ports -------------------------------
    gt3_cpllfbclklost_out           =>      gt_cpllfbclklost_out(3),
    gt3_cplllock_out                =>      gt_cplllock_out(3),
    gt3_cplllockdetclk_in           =>      DRP_CLK_IN,
    gt3_cpllpd_in                   =>      gt_cpllpd_in(3),
    gt3_cpllreset_in                =>      gt_cpllreset_in(3),
    -------------------------- Channel - Clocking Ports ------------------------
    gt3_gtgrefclk_in                =>      gt_gtgrefclk_in(3),
    gt3_gtnorthrefclk0_in           =>      gt_gtnorthrefclk0_in(3),
    gt3_gtnorthrefclk1_in           =>      gt_gtnorthrefclk1_in(3),
    gt3_gtrefclk0_in                =>      gt_refclk_in,
    gt3_gtrefclk1_in                =>      gt_gtrefclk1_in(3),
    gt3_gtsouthrefclk0_in           =>      gt_gtsouthrefclk0_in(3),
    gt3_gtsouthrefclk1_in           =>      gt_gtsouthrefclk1_in(3),
    ---------------------------- Channel - DRP Ports  --------------------------
    gt3_drpaddr_in                  =>      gt_drpaddr_in(3),
    gt3_drpclk_in                   =>      DRP_CLK_IN,
    gt3_drpdi_in                    =>      gt_drpdi_in(3),
    gt3_drpdo_out                   =>      gt_drpdo_out(3),
    gt3_drpen_in                    =>      gt_drpen_in(3),
    gt3_drprdy_out                  =>      gt_drprdy_out(3),
    gt3_drpwe_in                    =>      gt_drpwe_in(3),
    --------------------- RX Initialization and Reset Ports --------------------
    gt3_eyescanreset_in             =>      gt_eyescanreset_in(3),
    gt3_rxuserrdy_in                =>      gt_rxuserrdy_in(3),
    -------------------------- RX Margin Analysis Ports ------------------------
    gt3_eyescandataerror_out        =>      gt_eyescandataerror_out(3),
    gt3_eyescantrigger_in           =>      gt_eyescantrigger_in(3),
    ------------------- Receive Ports - Digital Monitor Ports ------------------
    gt3_dmonitorout_out             =>      gt_dmonitorout_out(3),
    ------------------ Receive Ports - FPGA RX Interface Ports -----------------
    gt3_rxusrclk_in                 =>      gt_rxusrclk_in,
    gt3_rxusrclk2_in                =>      gt_rxusrclk2_in,
    ------------------ Receive Ports - FPGA RX interface Ports -----------------
    gt3_rxdata_out                  =>      gt_rxdata_out(3),
    ------------------ Receive Ports - RX 8B/10B Decoder Ports -----------------
    gt3_rxdisperr_out               =>      gt_rxdisperr_out(3),
    gt3_rxnotintable_out            =>      gt_rxnotintable_out(3),
    ------------------------ Receive Ports - RX AFE Ports ----------------------
    gt3_gthrxn_in                   =>      gt_gthrxn_in(3),
    ------------------- Receive Ports - RX Buffer Bypass Ports -----------------
    gt3_rxbufstatus_out             =>      gt_rxbufstatus_out(3),
    gt3_rxphmonitor_out             =>      gt_rxphmonitor_out(3),
    gt3_rxphslipmonitor_out         =>      gt_rxphslipmonitor_out(3),
    -------------- Receive Ports - RX Byte and Word Alignment Ports ------------
    gt3_rxbyteisaligned_out         =>      gt_rxbyteisaligned_out(3),
    gt3_rxbyterealign_out           =>      gt_rxbyterealign_out(3),
    gt3_rxcommadet_out              =>      gt_rxcommadet_out(3),
    gt3_rxmcommaalignen_in          =>      gt_rxmcommaalignen_in(3),
    gt3_rxpcommaalignen_in          =>      gt_rxpcommaalignen_in(3),
    --------------------- Receive Ports - RX Equalizer Ports -------------------
    gt3_rxmonitorout_out            =>      gt_rxmonitorout_out(3),
    gt3_rxmonitorsel_in             =>      gt_rxmonitorsel_in(3),
    --------------- Receive Ports - RX Fabric Output Control Ports -------------
    gt3_rxoutclk_out                =>      open,
    ------------- Receive Ports - RX Initialization and Reset Ports ------------
    gt3_gtrxreset_in                =>      gt_gtrxreset_in(3),
    gt3_rxpcsreset_in               =>      gt_rxpcsreset_in(3),
    gt3_rxpmareset_in               =>      gt_rxpmareset_in(3),
    ----------------- Receive Ports - RX Polarity Control Ports ----------------
    gt3_rxpolarity_in               =>      gt_rxpolarity_in(3),
    ------------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    gt3_rxchariscomma_out           =>      gt_rxchariscomma_out(3),
    gt3_rxcharisk_out               =>      gt_rxcharisk_out(3),
    ------------------------ Receive Ports -RX AFE Ports -----------------------
    gt3_gthrxp_in                   =>      gt_gthrxp_in(3),
    -------------- Receive Ports -RX Initialization and Reset Ports ------------
    gt3_rxresetdone_out             =>      gt_rxresetdone_out(3),
    --------------------- TX Initialization and Reset Ports --------------------
    gt3_gttxreset_in                =>      gt_gttxreset_in(3),
    
    gt0_qplloutclk_in => '0',
    gt0_qplloutrefclk_in => '0'
);



end RTL;

